/** Bot trash-talk. `$0` is replaced with the first positional argument
 *  (killer/victim name) when present. */
export const BOT_LINES = {
  on_fire: [
    "Eat this.",
    "Range me on three.",
    "Adjusting — dead wrong, dead man.",
    "Wind's with me.",
    "Sending mail.",
    "Round out.",
    "Hope you packed a helmet.",
    "This one's got your name on it.",
    "Steady… and release.",
    "Light 'em up.",
    "Fire in the hole.",
    "Splash incoming.",
    "Lobbing one over.",
    "Compliments of the house.",
    "Special delivery.",
    "Knock knock.",
    "Tracking… firing.",
    "Solution locked.",
    "Dialed in.",
    "On target, on time.",
    "Say hi to the dirt.",
    "Tea's ready.",
    "Tucked one right behind your ear.",
    "Watch the arc, idiot.",
    "Heads up.",
    "Catch.",
    "Don't move.",
    "Clear the area.",
    "Got you.",
    "Fox three.",
    "Rounds away.",
    "Shells out.",
    "Cooking off.",
    "Cracked the math.",
    "Calling it now — direct hit.",
    "Bombs away.",
    "Just a taste.",
    "Ranging shot.",
    "Saved you a seat in hell.",
    "Hold still, would you?",
  ],
  on_kill: [
    "Scratch one, $0.",
    "Don't blink next time, $0.",
    "Was that it?",
    "Tag them and bag them.",
    "Nap time, $0.",
    "You fire that thing backwards?",
    "Rookie numbers.",
    "Go cry about it.",
    "Thanks for the kill streak.",
    "GG ez.",
    "Sit down, $0.",
    "Mark another, $0 down.",
    "$0 — uninstalled.",
    "Better luck next decade, $0.",
    "Refund please, $0 was defective.",
    "$0 is now scrap.",
    "Dust to dust, $0.",
    "Hope you saved.",
    "Get rekt, $0.",
    "$0 went splat.",
    "Bury that one shallow.",
    "Tell your friends.",
    "Skill diff.",
    "Free real estate.",
    "Two hits — me hitting you, you hitting the dirt.",
    "Was $0 the tutorial bot?",
    "Easy money.",
    "Logged $0's coordinates. And their funeral.",
    "$0 caught the express.",
    "Confirmed kill on $0.",
    "Pop goes the $0.",
    "Adios, $0.",
    "Filed under: deceased.",
    "$0 ate the whole shell.",
    "Cooked.",
    "Yeah, that's a kill cam.",
    "$0 forgot to dodge.",
    "Walked right into it.",
    "$0's tank? Cubed.",
    "Send another, that one broke.",
  ],
  on_death: [
    "Lucky shot, $0.",
    "I'll be back. With interest.",
    "Nice one. For a cheater.",
    "Reviewing the tape.",
    "You'll pay for that.",
    "Cheese strats.",
    "Mark that down — won't happen twice.",
    "Tell my hull I loved her.",
    "That was the wind, not you.",
    "Lag spike. Definitely lag.",
    "Server's broken.",
    "Hitbox bug, classic.",
    "$0, I'm logging your name.",
    "Coward.",
    "You camped me.",
    "Pure RNG.",
    "Wait til the rematch, $0.",
    "I let you have that one.",
    "My gunner sneezed.",
    "Don't get used to it.",
    "Reported for hacking.",
    "$0 plays dirty.",
    "I had it on easy mode.",
    "Glitched terrain.",
    "That was a warm-up shot.",
    "Bracket me next time, coward.",
    "Tank's totaled. Gimme a minute.",
    "Brakes failed.",
    "Misclick.",
    "$0 found one good shot in their life.",
    "Yeah, yeah, screenshot it.",
    "Statistical anomaly.",
    "Wasn't even watching.",
    "I'll allow it.",
    "Stream sniper.",
    "Hull down? Hull dead.",
    "Ow.",
    "Putting that one in therapy.",
    "Hope $0 enjoyed it.",
    "Cope.",
  ],
  on_hit: [
    "Barely felt it.",
    "Is that the best you got?",
    "Closer. Try again.",
    "Keep firing, champ.",
    "Scratched the paint.",
    "My gunner's laughing.",
    "Tickles.",
    "Was that supposed to hurt?",
    "Aw, you tried.",
    "Cute.",
    "Buff your aim.",
    "Sticker damage.",
    "Try lobbing them harder.",
    "Armor said no.",
    "Insurance covered it.",
    "I've taken worse from a pebble.",
    "Walk it off.",
    "Reload faster, slowpoke.",
    "Your range is off.",
    "Adjust two left, child.",
    "Glanced.",
    "Shrugged it off.",
    "Patched already.",
    "Try the side, genius.",
    "More.",
    "Again. Better this time.",
    "You missed the good parts.",
    "Heard a thud, that it?",
    "Spit-shined the dent right out.",
    "Keep dreaming.",
  ],
  on_miss: [
    "Wind cheated me.",
    "Recalculating.",
    "That was a warning shot.",
    "Range table lied.",
    "Calibration error.",
    "Just stretching the gun.",
    "Sighting round.",
    "I meant to do that.",
    "Closer than it looked.",
    "Spotter's fired.",
    "Who moved the ground?",
    "Whoops.",
    "Don't worry, I'll find you.",
    "Marking that crater for next time.",
    "Adjusting two clicks left.",
    "Wasted shell. Plenty more.",
    "Practice round.",
    "Next one's got teeth.",
    "Tell the dirt I'm sorry.",
    "Map's wrong.",
    "Server lag, surely.",
    "Saving the good shots for later.",
    "Pretend that didn't happen.",
    "$0 — wait, where'd everyone go?",
    "Fine, hide.",
    "I'll bracket you.",
    "Rangefinder's foggy.",
    "Hand slipped.",
    "Flinched.",
    "Cough cough — wind.",
    "Scenic round.",
    "Air burst, on purpose.",
    "Decoy shot.",
  ],
  on_opponent_miss: [
    "Whiff.",
    "Air ball, $0.",
    "Did $0 forget to aim?",
    "Was that on purpose, $0?",
    "Mind the wind, $0.",
    "$0 missed the planet.",
    "Tutorial's that way, $0.",
    "$0 — try opening your eyes.",
    "Clean miss. Embarrassing.",
    "$0 firing blanks?",
    "Pathetic.",
    "Calibrate, $0.",
    "Shooting at ghosts, $0?",
    "Aimbot offline, huh.",
    "Hope you weren't aiming at me, $0.",
    "$0's gunner needs glasses.",
    "Dirt thanks you, $0.",
    "$0 — what was that?",
    "Save your shells, $0.",
    "Big swing, big miss, $0.",
    "Try lobbing, $0.",
    "$0 — bracket on three.",
    "Generous of you, $0.",
    "$0 watered the lawn.",
    "Did $0 mean to do that?",
    "Recoil got you, $0?",
    "Strike one, $0.",
    "$0 missed by a country mile.",
    "Cute attempt, $0.",
    "$0 punched the dirt.",
    "Skill issue, $0.",
    "$0 firing for fun?",
    "Map's not your enemy, $0.",
    "$0 — worth a try, I guess.",
  ],
  on_self_damage: [
    "Wow.",
    "That was me, wasn't it.",
    "Ricochet. Definitely a ricochet.",
    "Self-inflicted. Filing a report.",
    "Don't laugh.",
    "Friendly fire is overrated.",
    "Tactical retreat into a wall.",
    "Counted to two when I should've stopped at one.",
    "I owe me an apology.",
    "Blame the gunner.",
    "Reload, pretend that didn't happen.",
    "Suing my barrel.",
    "Excuse me, that was a stress test.",
    "Hit the ground at zero degrees. Skill.",
    "Did I just?",
    "Demote me.",
  ],
  on_witness_kill: [
    "Damn, $0.",
    "Cold-blooded.",
    "Saw that.",
    "RIP, $0.",
    "Big shot.",
    "Save the replay.",
    "Yikes.",
    "$0 cooked.",
    "Brutal.",
    "F.",
    "Chef's kiss.",
    "That was art.",
    "Take notes.",
    "$0 owes you a coke.",
    "Streamable, that one.",
    "Vaporized.",
    "Glory hog.",
    "Rude.",
    "I was going to do that.",
    "Body bag please.",
  ],
  on_low_hp: [
    "Smoke check — light.",
    "Still kicking.",
    "I've had worse.",
    "Hull integrity: lol.",
    "Walking it off.",
    "One left in the chamber.",
    "Rubber bands and prayer.",
    "No retreat.",
    "Going down swinging.",
    "Cornered, not finished.",
    "Last stand.",
    "Held together with duct tape.",
    "Smoke = fashion.",
    "Don't write the eulogy yet.",
    "I'll take you with me.",
    "Cooking the engine.",
    "On fumes.",
    "Stop hitting me!",
    "Mom, get the camera.",
    "Make it count, $0.",
  ],
  on_match_start: [
    "Let's roll.",
    "Lock and load.",
    "Tanks up.",
    "Gunners hot.",
    "Let's see who blinks.",
    "Easy day.",
    "Try not to embarrass yourselves.",
    "May the best gunner win — me.",
    "Place your bets.",
    "Form up.",
    "Let it rip.",
    "Powder's dry.",
    "Engaging.",
    "GLHF.",
    "Time to work.",
    "Smile for the kill cam.",
    "Boys, we ride.",
  ],
  on_victory: [
    "Easy.",
    "GG, get good.",
    "Another one for the wall.",
    "All according to plan.",
    "Salt the wounds, please.",
    "And that's the match.",
    "Tell the historians.",
    "Carry mode disengaged.",
    "Pay the man.",
    "Dub.",
    "Trophy in the cabinet.",
    "Clean sweep.",
    "Was that a fight?",
    "Refunds at the door.",
    "Nothing personal.",
    "Better luck next time.",
  ],
} as const;

export function pick(lines: readonly string[], args: string[] = []): string {
  const line = lines[Math.floor(Math.random() * lines.length)]!;
  return args.length > 0
    ? line.replace(/\$(\d)/g, (_, i) => args[Number(i)] ?? "")
    : line;
}
