/** Bot trash-talk. `$0` is replaced with the first positional argument
 *  (killer/victim name) when present. */
export const BOT_LINES = {
  on_fire: [
    "Eat this.",
    "Range me on three.",
    "Adjusting — dead wrong, dead man.",
    "Wind's with me.",
    "Sending mail.",
    "Round out.",
    "Hope you packed a helmet.",
    "This one's got your name on it.",
    "Steady… and release.",
    "Light 'em up.",
    "Fire in the hole.",
    "Splash incoming.",
    "Lobbing one over.",
    "Compliments of the house.",
    "Special delivery.",
    "Knock knock.",
    "Tracking… firing.",
    "Solution locked.",
    "Dialed in.",
    "On target, on time.",
    "Say hi to the dirt.",
    "Tea's ready.",
    "Tucked one right behind your ear.",
    "Watch the arc, idiot.",
    "Heads up.",
    "Catch.",
    "Don't move.",
    "Clear the area.",
    "Got you.",
    "Fox three.",
    "Rounds away.",
    "Shells out.",
    "Cooking off.",
    "Cracked the math.",
    "Calling it now — direct hit.",
    "Bombs away.",
    "Just a taste.",
    "Ranging shot.",
    "Saved you a seat in hell.",
    "Hold still, would you?",
    "Mortar's mad today.",
    "Shell's got opinions.",
    "Posting one airmail.",
    "Trajectory looks lethal.",
    "Eat parabola.",
    "Bracketed and cracked.",
    "One in the chamber, one in your skull.",
    "Cooking a hot one.",
    "Shoot first, gloat later.",
    "Hold my barrel.",
    "Ranging walked in.",
    "Smile, you're on shellcam.",
    "Powder's hungry.",
    "Sending regards.",
    "Plotted, locked, lobbed.",
    "Fuse is laughing.",
    "Round's already left, dummy.",
    "Mark this crater.",
    "Catch this with your face.",
  ],
  on_kill: [
    "Scratch one, $0.",
    "Don't blink next time, $0.",
    "Was that it?",
    "Tag them and bag them.",
    "Nap time, $0.",
    "You fire that thing backwards?",
    "Rookie numbers.",
    "Go cry about it.",
    "Thanks for the kill streak.",
    "GG ez.",
    "Sit down, $0.",
    "Mark another, $0 down.",
    "$0 — uninstalled.",
    "Better luck next decade, $0.",
    "Refund please, $0 was defective.",
    "$0 is now scrap.",
    "Dust to dust, $0.",
    "Hope you saved.",
    "Get rekt, $0.",
    "$0 went splat.",
    "Bury that one shallow.",
    "Tell your friends.",
    "Skill diff.",
    "Free real estate.",
    "Two hits — me hitting you, you hitting the dirt.",
    "Was $0 the tutorial bot?",
    "Easy money.",
    "Logged $0's coordinates. And their funeral.",
    "$0 caught the express.",
    "Confirmed kill on $0.",
    "Pop goes the $0.",
    "Adios, $0.",
    "Filed under: deceased.",
    "$0 ate the whole shell.",
    "Cooked.",
    "Yeah, that's a kill cam.",
    "$0 forgot to dodge.",
    "Walked right into it.",
    "$0's tank? Cubed.",
    "Send another, that one broke.",
    "$0 just got demoted.",
    "Folded $0 like laundry.",
    "Tag $0, ship $0.",
    "$0 — minus one tank.",
    "$0 caught a haymaker.",
    "Roof over $0's head? Gone.",
    "Wrote $0's obituary in shrapnel.",
    "$0 deleted from the lobby.",
    "$0 — taxidermy class.",
    "$0 just kissed a shell.",
    "Punched $0's ticket.",
    "$0's K/D took a hit.",
    "Buh-bye, $0.",
    "$0, that's a wrap.",
    "Marked $0 down for the dirt nap.",
    "$0 — Swiss cheese.",
    "Flattened $0.",
    "Notarized $0's death certificate.",
    "$0 down, $0 stays down.",
  ],
  on_death: [
    "Lucky shot, $0.",
    "I'll be back. With interest.",
    "Nice one. For a cheater.",
    "Reviewing the tape.",
    "You'll pay for that.",
    "Cheese strats.",
    "Mark that down — won't happen twice.",
    "Tell my hull I loved her.",
    "That was the wind, not you.",
    "Lag spike. Definitely lag.",
    "Server's broken.",
    "Hitbox bug, classic.",
    "$0, I'm logging your name.",
    "Coward.",
    "You camped me.",
    "Pure RNG.",
    "Wait til the rematch, $0.",
    "I let you have that one.",
    "My gunner sneezed.",
    "Don't get used to it.",
    "Reported for hacking.",
    "$0 plays dirty.",
    "I had it on easy mode.",
    "Glitched terrain.",
    "That was a warm-up shot.",
    "Bracket me next time, coward.",
    "Tank's totaled. Gimme a minute.",
    "Brakes failed.",
    "Misclick.",
    "$0 found one good shot in their life.",
    "Yeah, yeah, screenshot it.",
    "Statistical anomaly.",
    "Wasn't even watching.",
    "I'll allow it.",
    "Stream sniper.",
    "Hull down? Hull dead.",
    "Ow.",
    "Putting that one in therapy.",
    "Hope $0 enjoyed it.",
    "Cope.",
    "Wind shear, not skill.",
    "Sun was in my eyes.",
    "$0 — enjoy your fluke.",
    "Game's rigged.",
    "$0 timed out my hitbox.",
    "Taking that one personally.",
    "Mark me up, I'm bleeding hex.",
    "Server tickrate strikes again.",
    "Rematch, $0. Now.",
    "Cheap shot. Filed.",
    "Was reloading, $0.",
    "$0 borrowed someone else's aim.",
    "Gunner traitor.",
    "Powder was wet.",
    "Whole thing was scripted.",
    "$0 — ten bucks says you can't repeat that.",
    "Suspend $0's account.",
    "I'll see you in the next match, $0.",
    "Memorize that one, $0. Won't see it again.",
  ],
  on_hit: [
    "Barely felt it.",
    "Is that the best you got?",
    "Closer. Try again.",
    "Keep firing, champ.",
    "Scratched the paint.",
    "My gunner's laughing.",
    "Tickles.",
    "Was that supposed to hurt?",
    "Aw, you tried.",
    "Cute.",
    "Buff your aim.",
    "Sticker damage.",
    "Try lobbing them harder.",
    "Armor said no.",
    "Insurance covered it.",
    "I've taken worse from a pebble.",
    "Walk it off.",
    "Reload faster, slowpoke.",
    "Your range is off.",
    "Adjust two left, child.",
    "Glanced.",
    "Shrugged it off.",
    "Patched already.",
    "Try the side, genius.",
    "More.",
    "Again. Better this time.",
    "You missed the good parts.",
    "Heard a thud, that it?",
    "Spit-shined the dent right out.",
    "Keep dreaming.",
    "Mosquito bite.",
    "Felt like a hug.",
    "Did something hit me?",
    "Aw, you're trying.",
    "Buff polished it out.",
    "That's all you got?",
    "Static cling.",
    "Hull's bored.",
    "Slap fight, huh.",
    "Tap, tap. Boring.",
    "Try the other side.",
    "Felt like rain.",
    "Bring a bigger gun.",
    "Pillow round?",
    "Bored already.",
    "Hit harder, child.",
    "Painted over it.",
    "Polish, not penetration.",
    "Negligible.",
  ],
  on_miss: [
    "Wind cheated me.",
    "Recalculating.",
    "That was a warning shot.",
    "Range table lied.",
    "Calibration error.",
    "Just stretching the gun.",
    "Sighting round.",
    "I meant to do that.",
    "Closer than it looked.",
    "Spotter's fired.",
    "Who moved the ground?",
    "Whoops.",
    "Don't worry, I'll find you.",
    "Marking that crater for next time.",
    "Adjusting two clicks left.",
    "Wasted shell. Plenty more.",
    "Practice round.",
    "Next one's got teeth.",
    "Tell the dirt I'm sorry.",
    "Map's wrong.",
    "Server lag, surely.",
    "Saving the good shots for later.",
    "Pretend that didn't happen.",
    "Fine, hide.",
    "I'll bracket you.",
    "Rangefinder's foggy.",
    "Hand slipped.",
    "Flinched.",
    "Cough cough — wind.",
    "Scenic round.",
    "Air burst, on purpose.",
    "Decoy shot.",
    "Wait, where'd everyone go?",
    "That's on the wind.",
    "Gunner had one job.",
    "Shell ducked.",
    "Did the math, math lied.",
    "Drift's brutal today.",
    "Round took a vacation.",
    "Sniffed the wrong coordinates.",
    "Range card's a coaster.",
    "Wind betrayed me.",
    "Test fire, technically.",
    "Slipped a digit.",
    "Atmosphere's broken.",
    "Forgot to carry the one.",
    "I'll allow it. Once.",
    "Compass spun.",
    "Stupid trees.",
    "Charity round.",
    "Map glitched, I swear.",
    "Mulligan.",
  ],
  on_opponent_miss: [
    "Whiff.",
    "Air ball, $0.",
    "Did $0 forget to aim?",
    "Was that on purpose, $0?",
    "Mind the wind, $0.",
    "$0 missed the planet.",
    "Tutorial's that way, $0.",
    "$0 — try opening your eyes.",
    "Clean miss. Embarrassing.",
    "$0 firing blanks?",
    "Pathetic.",
    "Calibrate, $0.",
    "Shooting at ghosts, $0?",
    "Aimbot offline, huh.",
    "Hope you weren't aiming at me, $0.",
    "$0's gunner needs glasses.",
    "Dirt thanks you, $0.",
    "$0 — what was that?",
    "Save your shells, $0.",
    "Big swing, big miss, $0.",
    "Try lobbing, $0.",
    "$0 — bracket on three.",
    "Generous of you, $0.",
    "$0 watered the lawn.",
    "Did $0 mean to do that?",
    "Recoil got you, $0?",
    "Strike one, $0.",
    "$0 missed by a country mile.",
    "Cute attempt, $0.",
    "$0 punched the dirt.",
    "Skill issue, $0.",
    "$0 firing for fun?",
    "Map's not your enemy, $0.",
    "$0 — worth a try, I guess.",
    "Bricks in the barrel, $0?",
    "$0 aimed with feet.",
    "$0's gunner: drunk.",
    "Read the wind, $0.",
    "$0 fired at clouds.",
    "$0 — shells aren't free.",
    "Bold strategy, $0.",
    "$0 just bombed a butterfly.",
    "Try again, $0. Slower.",
    "$0 watered a tree.",
    "$0 — your range is fiction.",
    "Sad, $0.",
    "$0 — was that aimed?",
    "$0's compass says nope.",
    "Public service announcement: $0 missed.",
    "$0 firing into the void.",
    "$0's tutorial expired.",
    "Tilt confirmed, $0.",
    "$0 brought a slingshot.",
    "$0 — embarrassment of riches. The riches being whiffs.",
  ],
  on_self_damage: [
    "Wow.",
    "That was me, wasn't it.",
    "Ricochet. Definitely a ricochet.",
    "Self-inflicted. Filing a report.",
    "Don't laugh.",
    "Friendly fire is overrated.",
    "Tactical retreat into a wall.",
    "Counted to two when I should've stopped at one.",
    "I owe me an apology.",
    "Blame the gunner.",
    "Reload, pretend that didn't happen.",
    "Suing my barrel.",
    "Excuse me, that was a stress test.",
    "Hit the ground at zero degrees. Skill.",
    "Did I just?",
    "Demote me.",
    "Owned myself. Speedrun.",
    "Fired the wrong way. Fantastic.",
    "Hull says 'why'.",
    "Court-martial pending.",
    "Did the angle backwards.",
    "Negative skill.",
    "Tactical self-own.",
    "Erase that from the replay.",
    "Hit my own roof. Cool.",
    "I'd refund myself if I could.",
    "Engineer fired, immediately.",
    "Backstrap to the chin.",
    "Recoil therapy.",
    "Note to self: aim outward.",
    "Whoops, that's me.",
    "Filed under: skill issue.",
    "I peer-pressured myself.",
    "Tank wants a divorce.",
  ],
  on_witness_kill: [
    "Damn, $0.",
    "Cold-blooded.",
    "Saw that.",
    "RIP, $0.",
    "Big shot.",
    "Save the replay.",
    "Yikes.",
    "$0 cooked.",
    "Brutal.",
    "F.",
    "Chef's kiss.",
    "That was art.",
    "Take notes.",
    "$0 owes you a coke.",
    "Streamable, that one.",
    "Vaporized.",
    "Glory hog.",
    "Rude.",
    "I was going to do that.",
    "Body bag please.",
    "Surgical, $0.",
    "$0 went hunting.",
    "Mount that one.",
    "Frame it, $0.",
    "$0 with the slap.",
    "Tape rolling, $0?",
    "Nice arc, $0.",
    "Dirty work, $0. Approved.",
    "$0 cooking.",
    "Cold, $0. Cold.",
    "Witness me — to $0's kill.",
    "$0 sniped from orbit.",
    "Scoreboard checked. $0 ahead.",
    "$0 — pure spite.",
    "Disrespectful. Beautiful.",
    "$0 sent them home.",
    "Highlight reel, $0.",
    "Damn, that lobbed.",
    "$0 collected the head.",
  ],
  on_low_hp: [
    "Smoke check — light.",
    "Still kicking.",
    "I've had worse.",
    "Hull integrity: lol.",
    "Walking it off.",
    "One left in the chamber.",
    "Rubber bands and prayer.",
    "No retreat.",
    "Going down swinging.",
    "Cornered, not finished.",
    "Last stand.",
    "Held together with duct tape.",
    "Smoke = fashion.",
    "Don't write the eulogy yet.",
    "I'll take you with me.",
    "Cooking the engine.",
    "On fumes.",
    "Stop hitting me!",
    "Mom, get the camera.",
    "Make it count, $0.",
    "One pixel of HP, full pixel of spite.",
    "Crawling, not crying.",
    "Spitting sparks.",
    "Engine on fire, ego intact.",
    "Hull's a colander.",
    "Bleeding diesel, fine.",
    "Last shell, best shell.",
    "Out of ammo, full of grudge.",
    "Wreckage with attitude.",
    "Tank's praying.",
    "If I die, I'm taking the lobby.",
    "Smoke screen — accidental.",
    "Treads are toothpicks.",
    "Patched with tape and rage.",
    "Crawling crit, baby.",
    "Limp mode: engaged.",
    "Going out loud.",
    "Make the last one matter.",
    "Don't write me off, $0.",
  ],
  on_match_start: [
    "Let's roll.",
    "Lock and load.",
    "Tanks up.",
    "Gunners hot.",
    "Let's see who blinks.",
    "Easy day.",
    "Try not to embarrass yourselves.",
    "May the best gunner win — me.",
    "Place your bets.",
    "Form up.",
    "Let it rip.",
    "Powder's dry.",
    "Engaging.",
    "GLHF.",
    "Time to work.",
    "Smile for the kill cam.",
    "Boys, we ride.",
    "Engines hot.",
    "Crews up.",
    "Battery acid in the veins.",
    "Don't waste my time.",
    "Powder, primer, prayer.",
    "Coffee's cold, gun's hot.",
    "Tap that mini-map.",
    "Fight starts in three.",
    "Bring something this round.",
    "Hold the line, lobby.",
    "Eyes up, gunners.",
    "Shake hands — then break tanks.",
    "Range cards out.",
    "Throttle to the floor.",
    "Salute and shoot.",
    "Wind check, then murder.",
    "Whoever ducks first wins.",
    "Last one standing eats steak.",
  ],
  on_victory: [
    "Easy.",
    "GG, get good.",
    "Another one for the wall.",
    "All according to plan.",
    "Salt the wounds, please.",
    "And that's the match.",
    "Tell the historians.",
    "Carry mode disengaged.",
    "Pay the man.",
    "Dub.",
    "Trophy in the cabinet.",
    "Clean sweep.",
    "Was that a fight?",
    "Refunds at the door.",
    "Nothing personal.",
    "Better luck next time.",
    "Case closed.",
    "Smoke 'em if you got 'em.",
    "Trophy polished.",
    "Curtains.",
    "Lobby's mine.",
    "Notch the barrel.",
    "GG, no re.",
    "Stack the bodies, count the dub.",
    "Champagne for one.",
    "Print the W.",
    "All gas, no brakes.",
    "Pencil that in.",
    "Domination, registered.",
    "Match? Solved.",
    "Salt mines open for business.",
    "Take notes, lobby.",
    "Owned the field.",
    "Round complete. Egos shattered.",
  ],
} as const;

export function pick(lines: readonly string[], args: string[] = []): string {
  const line = lines[Math.floor(Math.random() * lines.length)]!;
  // Always strip placeholders so a stray $N in a no-args line doesn't leak.
  return line.replace(/\$(\d)/g, (_, i) => args[Number(i)] ?? "");
}
